### ISSUE TITLE
Random Tip from a BASH Geek

### ISSUE THREAD

**Issue by ghost** [ydhamija96/config#9]
These lines are probably more suited to '\~/.inputrc'; it might help keep your '\~/.bashrc' a bit tighter, if that's a concern of yours. Lol

https://github.com/yogeshdhamija/dotfiles/blob/78a5c2aceb3f588924b2c02beab796a8dd6df108/.bashrc#L17-L20

Plus, you can use some neat logic for just that file:

```
$if mode=emacs
    "\e[A": history-search-backward' 
    "\e[B": history-search-forward' 
    "\C-F": forward-word' 
    "\C-B": backward-word'
$endif
```

I use something similar in mine.

By the way, on the off-chance you're not already aware of this: there should already be a shortcut _Ctrl + N_ and _Ctrl + P_ for browsing to the next and previous history entry, respectively. Unless that's just something I have in my configuration somewhere.

**Comment by yogeshdhamija** [comment]
Cool! I'll look into inputrc vs. bashrc. I don't think I have inputrc committed-- haven't messed around with that yet.

**Comment by yogeshdhamija** [comment]
Closing due to lack of desire to commit yet another `*.rc` file
